FROM python:3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate


COPY . .

CMD ["gunicorn", "config.wsgi", "--bind", "0.0.0.0:8000"]