FROM python:3.9

WORKDIR /app
RUN apt-get update
RUN apt-get -y install python-pip
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install psycopg2-binary
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate


COPY . .

CMD ["gunicorn", "config.wsgi", "--bind", "0.0.0.0:8000"]