
release: python manage.py migrate
      && python manage.py createsuperuser --noinput --username admin --email admin@example.com
      && python manage.py collectstatic --noinput
web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT