import type { Metadata } from "next";
import { Nunito, Raleway } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap',
})

const raleway = Raleway({
  subsets: ['latin', 'cyrillic'],
  weight: ['700'], // Укажите нужные начертания
  variable: '--font-raleway', // (опционально) для использования CSS-переменной
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${nunito.className}  ${raleway.className} antialiased max-w-screen`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          {/* <Header/> */}
            {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
