import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Main } from "./components/main/Main";
import { Micro_5 } from 'next/font/google'
import { AppProvider } from "./components/provider/AppProvider";
import GridBackground from "./components/gridBackground";
import Head from "next/head";

const micro5 = Micro_5({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-pixel'
})


const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-quicksand',
});


export const metadata: Metadata = {
  title: "Tile web-site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru">
      <Head>
      <meta name="mobile-web-app-capable" content="yes" />
        
        {/* Для iOS */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="My PWA" />
        
        {/* Для Windows */}
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-TileImage" content="/icons/ms-icon-144x144.png" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
        
        {/* Viewport */}
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />
        <title>My Next.js PWA</title>
      </Head>
      <body
        className={`${quicksand.variable} ${micro5.variable}`} 
        style={{fontFamily: 'var(--font-quicksand)'}}
      >  
        <GridBackground/>
        <AppProvider className="m-auto sm:p-3 overflow-hidden h-screen border border-white">
          <Main/>
        </AppProvider>
        {children}
      </body>
    </html>
  );
}
