import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Main } from "./components/main/Main";
import { Micro_5 } from 'next/font/google'
import { AppProvider } from "./components/provider/AppProvider";
import GridBackground from "./components/gridBackground";

const micro5 = Micro_5({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-pixel'
})


const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-quicksand',
});


export const metadata: Metadata = {
  title: "Tile web-site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru">
      <body
        className={`${quicksand.variable} ${micro5.variable}`} 
        style={{fontFamily: 'var(--font-quicksand)'}}
      >  
        <GridBackground/>
        <AppProvider className="m-auto sm:p-3 overflow-hidden h-screen border border-white">
          <Main/>
        </AppProvider>
        {children}
      </body>
    </html>
  );
}
